export const REQUEST_CONTRACTS = 'REQUEST_CONTRACTS'
export const RECEIVE_CONTRACTS = 'RECEIVE_CONTRACTS'
export const MAP_OPTIONS = 'MAP_OPTIONS'
export const FOCUS_CONTRACT = 'FOCUS_CONTRACT'

export const REQUEST_BOOK_TOPS = 'REQUEST_BOOK_TOPS'
export const RECEIVE_BOOK_TOPS = 'RECEIVE_BOOK_TOPS'

export const NETWORK_ERROR = 'NETWORK_ERROR'

export const WS_CONNECT = 'WS_CONNECT'
export const WS_CONNECTING = 'WS_CONNECTING'
export const WS_CONNECTED = 'WS_CONNECTED'
export const WS_DISCONNECT = 'WS_DISCONNECT'
export const WS_DISCONNECTED = 'WS_DISCONNECTED'
export const UPDATE_BOOK_TOP = 'UPDATE_BOOK_TOP'
